kind: List
apiVersion: v1
items:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: monitoring-sa
    namespace: monitoring

- apiVersion: rbac.authorization.k8s.io/v1
  kind: Role
  metadata:
    name: default-role
    namespace: default
  rules:
    - apiGroups: [""] # "" refers to the core API group
      resources: ["services", "endpoints", "pods"]
      verbs: ["get", "list", "watch"]

- apiVersion: rbac.authorization.k8s.io/v1
  kind: Role
  metadata:
    name: monitoring-role
    namespace: monitoring
  rules:
    - apiGroups: [""] # "" refers to the core API group
      resources: ["services", "endpoints", "pods"]
      verbs: ["get", "list", "watch"]

- apiVersion: authorization.openshift.io/v1
  kind: RoleBinding
  metadata:
    name: monitoring-role-binding
    namespace: monitoring
  roleRef:
    name: monitoring-role
    namespace: monitoring
  subjects:
  - kind: ServiceAccount
    name: monitoring-sa
    namespace: monitoring




- apiVersion: authorization.openshift.io/v1
  kind: ClusterRoleBinding
  metadata:
    name: monitoring-clusterrole-binding
  roleRef:
    name: cluster-monitoring-view #basic-user
  subjects:
  - kind: ServiceAccount
    name: monitoring-sa

     


- apiVersion: authorization.openshift.io/v1
  kind: RoleBinding
  metadata:
    name: monitoring-role-binding
    namespace: monitoring
  roleRef:
    name: default-role
    namespace: default
  subjects:
  - kind: ServiceAccount
    name: monitoring-sa
    namespace: monitoring
